### PR TITLE
Ft models vincent

### PR DESCRIPTION
**Pull request by Vincent-Juma**
I've started removing unwanted file, so it's still on progress

### CODE REVIEW

**Comment by devsamuelmwangi** [comment]
Change base branch to development branch rather than master branch.

**Comment by Vincent-Juma** [comment]
Ok

**Comment by devsamuelmwangi** [comment]
# Contains deprecated code!

**Comment by devsamuelmwangi** [comment]
# Contains deprecated code!

**Comment by devsamuelmwangi** [comment]
# Contains deprecated code!

**Pull request closed without merging**
